name: Build and Deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: NewRetailApp   # Azure Web App name
  PYTHON_VERSION: '3.11'             # Python version

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 2dbb826a-3d55-4250-b9c0-ba1c3bd1b0b8
          tenant-id: f5222e6c-5fc6-48eb-8f03-73db18203b63
          subscription-id: d1b02253-bdbf-49fe-b947-b372bf8a229e
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: service-principal  # <-- This fixes the OIDC vs password login confusion

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
